// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvOkKrjBjd8lbxaSBnf7-mYloDeIw6wBM',
    appId: '1:1073374918140:web:da451c2d2304b6feb22e79',
    messagingSenderId: '1073374918140',
    projectId: 'mybooking1-2ede2',
    authDomain: 'mybooking1-2ede2.firebaseapp.com',
    storageBucket: 'mybooking1-2ede2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-A-aSGxVSgWcPNvl7uDYHVwBzqst4FQw',
    appId: '1:1073374918140:android:864d351d87d3b0c8b22e79',
    messagingSenderId: '1073374918140',
    projectId: 'mybooking1-2ede2',
    storageBucket: 'mybooking1-2ede2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgNpRlwzL3Tk2fGABa4zw--E3pnNf4f3c',
    appId: '1:1073374918140:ios:110bdd4f7419d0acb22e79',
    messagingSenderId: '1073374918140',
    projectId: 'mybooking1-2ede2',
    storageBucket: 'mybooking1-2ede2.appspot.com',
    androidClientId: '1073374918140-pbsb2lh6bcd41lb5u7j9ceciiqsi0hpl.apps.googleusercontent.com',
    iosClientId: '1073374918140-lrq3ur3rehg3aeppapibv1cju0abl24q.apps.googleusercontent.com',
    iosBundleId: 'com.example.bbooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgNpRlwzL3Tk2fGABa4zw--E3pnNf4f3c',
    appId: '1:1073374918140:ios:f90e8fd761ed4236b22e79',
    messagingSenderId: '1073374918140',
    projectId: 'mybooking1-2ede2',
    storageBucket: 'mybooking1-2ede2.appspot.com',
    androidClientId: '1073374918140-pbsb2lh6bcd41lb5u7j9ceciiqsi0hpl.apps.googleusercontent.com',
    iosClientId: '1073374918140-jvq06i1705othcq395j4eca5ibu44joh.apps.googleusercontent.com',
    iosBundleId: 'com.example.bbooking.RunnerTests',
  );
}
